# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 09:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20170316_1005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='productattribute',
            options={'verbose_name': 'Характеристика товара', 'verbose_name_plural': 'Характеристики Товаров'},
        ),
    ]
