# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20170316_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='catalog/categories_images/', verbose_name='Изображение категории'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='catalog/products_images/%Y/%m/%d/', verbose_name='Изображение товара'),
        ),
    ]
