# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 05:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0004_auto_20170322_0852'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=200, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('city', models.CharField(max_length=80, verbose_name='Город')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('postal_code', models.CharField(max_length=80, verbose_name='Почтовый индекс')),
                ('description', models.CharField(max_length=200, verbose_name='Краткое описание')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Дата оформления заказа')),
                ('updated', models.DateField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('when_paid', models.DateField(verbose_name='Дата оплаты')),
            ],
            options={
                'verbose_name': 'Заказ',
                'ordering': ['created'],
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderedProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за единицу')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество товара')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='orders.Order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='catalog.Product', verbose_name='Товар')),
            ],
        ),
    ]
