# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20170322_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='when_paid',
            field=models.DateField(default=None, null=True, verbose_name='Дата оплаты'),
        ),
    ]
